[package]
name = "kdtree"
version = "0.1.0"
authors = ["mrhooray <ruihu.pvt@gmail.com>"]
description = "K-dimensional tree for Rust(bucket point-region implementation)"
keywords = ["tree", "nearest", "dimension", "search", "geo"]
repository = "https://github.com/mrhooray/kdtree-rs"
license = "MIT"

[dev-dependencies]
rand = "~0.3.9"
